#!url=https://raw.githubusercontent.com/yang66887/AdBlock/main/adblock.module
#!name = 去牛皮藓
#!desc = 自用去广告
#!author = 蛋蛋の超人

[Rule]
DOMAIN-SUFFIX,adtroop.cn,Reject
DOMAIN-SUFFIX,ubixioe.com,Reject
DOMAIN-SUFFIX,umeng.com,Reject
DOMAIN-SUFFIX,umengcloud.com,Reject
DOMAIN-SUFFIX,zijieapi.com,Reject
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,Reject
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,Reject
DOMAIN-SUFFIX,volces.com,Reject
DOMAIN-SUFFIX,bytescm.com,Reject
DOMAIN-SUFFIX,byteurl.com,Reject
DOMAIN-SUFFIX,ctobsnssdk.com,Reject
DOMAIN-SUFFIX,youzan.com,Reject
DOMAIN-SUFFIX,youzanyun.com,Reject
DOMIAN-SUFFIX,yzcdn.cn,Reject
DOMAIN-SUFFIX,jiguang.cn,Reject
DOMAIN-SUFFIX,tianmu.mobi,Reject
DOMAIN-SUFFIX,admobile.top,Reject
DOMIAN-SUFFIX,admobile.mobi,Reject
DOMAIN-SUFFIX,admobile.cc,Reject
DOMAIN-SUFFIX,sohu.com,Reject
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,Reject
DOMAIN-SUFFIX,xd.cn,Reject
DOMAIN-SUFFIX,tagtic.cn,Reject
DOMAIN-SUFFIX,e.kuaishou.com,Reject
DOMAIN-SUFFIX,snssdk.com,Reject
DOMAIN-SUFFIX,yangkeduo.com,Reject

[URL Rewrite]
# 山丘阅读会员解锁
#^https?:\/\/m\.815616\.xyz\/(api\/v2\/istoken.*uid=)7aa16c9a8(.*)$ http://m.815616.xyz/$1c55s1d4c7$2 302
#^https?:\/\/m\.815616\.xyz\/api\/v2\/saveiaporder.*$ - Direct
#^https?:\/\/m\.815616\.xyz https://tv.superegg.buzz header

# 游民星空
^https?:\/\/appapi\d?click\.gamersky\.com.*$ - Reject
^https?:\/\/router\d?\.gamersky\.com\/@\/ad/.*$ - Reject
^https?:\/\/router\d?\.gamersky\.com\/@\/app/.*$ - Reject
^https?:\/\/router\d?\.gamersky\.com\/@\/userCenterPage\/.*$ - Reject
^https?:\/\/router\d?\.gamersky\.com\/@\/recommend.*$ - Reject
^https?:\/\/router\d?\.gamersky\.com\/@\/ad\/.*$ - Reject
^https?:\/\/appapi\d?\.gamersky\.com\/v5\/CheckLogin.*$ - Reject
#^https?:\/\/imgf.gamersky.com\/img\/tqbc.*$ - Reject
^https?:\/\/item-statistics\.gamersky\.com:8089\/statistics\/event.*$ - Reject

[Script]
游民星空去广告=type=http-response,pattern=^https?:\/\/router\d?\.gamersky\.com\/@\/lists\/getListElements,requires-body=1,script-path=https://raw.githubusercontent.com/yang66887/AdBlock/main/gamersky.js

[MITM]
hostname = %APPEND% *.google.cn,*.googlevideo.com,*.youtube.com,*.googleapis.com,*.gamersky.com,*.adtroop.cn,*.umeng.com,*.baidu.com,*.bilibili.com,*.bilivideo.com,*.ubixioe.com,*.zijieapi.com,*.xd.cn*.kuaishou.com,*.snssdk.com
