#!url=https://raw.githubusercontent.com/yang66887/AdBlock/main/adblock.module
#!name = 去牛皮藓
#!desc = 自用去除各类顽固三方广告以及App版面广告
#!author = 蛋蛋の超人

[Rule]
DOMAIN-SUFFIX,adtroop.cn,Reject
DOMAIN-SUFFIX,ubixioe.com,Reject
DOMAIN-SUFFIX,umeng.com,Reject
DOMAIN-SUFFIX,umengcloud.com,Reject
DOMAIN-SUFFIX,youzan.com,Reject
DOMAIN-SUFFIX,youzanyun.com,Reject
DOMIAN-SUFFIX,yzcdn.cn,Reject
DOMAIN-SUFFIX,jiguang.cn,Reject
DOMAIN-SUFFIX,tianmu.mobi,Reject
DOMAIN-SUFFIX,admobile.top,Reject
DOMIAN-SUFFIX,admobile.mobi,Reject
DOMAIN-SUFFIX,admobile.cc,Reject
DOMAIN-SUFFIX,sohu.com,Reject
DOMAIN-SUFFIX,xd.cn,Reject
DOMAIN-SUFFIX,tagtic.cn,Reject
DOMAIN-SUFFIX,e.kuaishou.com,Reject
DOMAIN-SUFFIX,yangkeduo.com,Reject
DOMAIN-SUFFIX,sigmob.cn,Reject
DOMAIN-SUFFIX,adukwai.com,Reject
DOMAIN-SUFFIX,zijieapi.com,reject-200
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,reject-200
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,reject-200
DOMAIN-SUFFIX,volces.com,reject-200
DOMAIN-SUFFIX,snssdk.com,reject-200
DOMAIN-SUFFIX,ctobsnssdk.com,reject-200
DOMAIN-SUFFIX,pglstatp-toutiao.com,reject-200
DOMAIN-SUFFIX,chengzijianzhan.com,reject-200
DOMAIN-SUFFIX,oceanengine.com,reject-200
DOMAIN-SUFFIX,bytetos.com,reject-200
DOMAIN-SUFFIX,bytescm.com,reject-200
DOMAIN-SUFFIX,byteurl.com,reject-200
DOMAIN-SUFFIX,1rtb.net,reject-200
DOMAIN-SUFFIX,1rtb.com,reject-200
DOMAIN-SUFFIX,bytedance.com,reject-200
DOMAIN-SUFFIX,douyinpic.com,reject-200
DOMAIN-SUFFIX,ugdtimg.com,reject-200
DOMAIN-SUFFIX,pangolin-sdk-toutiao-b.com,reject-200
# youtube
#DOMAIN-SUFFIX,ggpht.com,reject-200

[URL Rewrite]
# 游民星空
^https?:\/\/appapi[0-9]{0,}click\.gamersky\.com.*$ - Reject
^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/ad/.*$ - Reject
^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/app/.*$ - Reject
^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/userCenterPage\/.*$ - Reject
^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/recommend.*$ - Reject
^https?:\/\/appapi[0-9]{0,}\.gamersky\.com\/v5\/CheckLogin.*$ - Reject
^https?:\/\/item-statistics\.gamersky\.com:8089\/statistics\/event.*$ - Reject
^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/search/getRecommendSearchKeys/.*$ - Reject

[Script]
游民星空版面清理=type=http-response,pattern=^https?:\/\/router[0-9]{0,}\.gamersky\.com\/@\/(lists\/getListElements|homePage\/index),requires-body=1,script-path=https://raw.githubusercontent.com/yang66887/AdBlock/main/gamersky.js
JUMP版面清理=type=http-response,pattern=^https?:\/\/switch\.jumpvg\.com\/jump\/(interest_v2\/home|mainweb\/v3|community\/followUpdata|getlaunchad\/v2|app\/conf|recommend\/.*|favorite\/count_v2|favorite\/can_show_guide|favorite\/check_all_count),requires-body=1,script-path=https://raw.githubusercontent.com/yang66887/AdBlock/refs/heads/main/jump.js

[MITM]
hostname = %APPEND% *.google.cn,*.googlevideo.com,*.youtube.com,*.googleapis.com,*.gamersky.com,*.adtroop.cn,*.umeng.com,*.baidu.com,*.bilibili.com,*.bilivideo.com,*.ubixioe.com,*.xd.cn*.kuaishou.com
