#!url=https://raw.githubusercontent.com/yang66887/AdBlock/main/ngablock.module
#!name = NGA屏蔽插件
#!desc = 自用NGA屏蔽插件
#!author = 蛋蛋の超人

[URL Rewrite]
^https?:\/\/ngabbs\.com\/nuke\.php\?__lib=app_inter&__act=banner_list$ - Reject
^https?:\/\/ngabbs\.com\/nuke\.php\?__lib=nga_index&__act=get_event_app.*$ - Reject

[Script]
NGA屏蔽插件=type=http-response,pattern=^https?:\/\/ngabbs\.com\/app_api\.php\?__lib=subject&__act=list,requires-body=1,script-path=https://raw.githubusercontent.com/yang66887/AdBlock/main/ngaBlock.js

[MITM]
hostname = %APPEND% ngabbs.com
