#!url=https://raw.githubusercontent.com/yang66887/AdBlock/main/ngablock.module
#!name = NGA屏蔽插件
#!desc = 自用NGA屏蔽插件
#!author = 蛋蛋の超人

[URL Rewrite]
# 首页banner广告
^https?:\/\/ngabbs\.com\/nuke\.php\?__lib=app_inter&__act=(banner_list|recmd_topic)$ - REJECT-ARRAY
# 首页官方推荐
^https?:\/\/ngabbs\.com\/nuke\.php\?__lib=nga_index&__act=get_event_app.*$ - REJECT-ARRAY

[Script]

# 在线脚本，不可自行维护屏蔽关键字
#NGA屏蔽插件=type=http-response,pattern=^https?:\/\/ngabbs\.com\/app_api\.php\?__lib=(subject|post)&__act=list,requires-body=1,script-path=https://raw.githubusercontent.com/yang66887/AdBlock/main/ngablock.js

# 本地脚本（小火箭 → 配置 → 配置文件ⓘ → 脚本 → 右上角+ → 脚本路径ⓘ → 右上角+ → 脚本名称 → 粘贴代码 → 保存），可自行维护屏蔽关键字
NGA屏蔽插件=type=http-response,pattern=^https?:\/\/ngabbs\.com\/app_api\.php\?__lib=(subject|post)&__act=list,requires-body=1,script-path=ngablock.js

[MITM]
hostname = %APPEND% ngabbs.com
